
/* CRIA O BANCO DE DADOS, CASO ELE NÃO EXISTA: */
CREATE DATABASE IF NOT EXISTS db_cad_anuncio 
DEFAULT character SET utf8 -- CONJUNTO DE CARACTERES PADRÃO A SER USADO.
DEFAULT COLLATE utf8_general_ci; -- CONJUNTO DE CARACTERES ACENTUADOS.

/* SELECIONA O BANCO DE DADOS A SER UTILIZADO: */
USE db_cad_anuncio;

/* CRIA A TABELA ANUNCIO: */
CREATE TABLE ANUNCIO (
-- ID NÃO PODE SER NULO. PREENCHIDO AUTOMATICAMENTE:
ID INT NOT NULL AUTO_INCREMENT, 
NOME_ANUNCIO VARCHAR(80) NOT NULL,
CLIENTE VARCHAR(50) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_TERMINO DATE NOT NULL,
-- NÃO ACEITA VALORES NEGATIVOS:
VALOR_INVEST_DIA INT UNSIGNED NOT NULL, 

-- DECLARA A CHAVE PRIMÁRIA DA TABELA:
PRIMARY KEY (ID) 
-- PADRÃO DE CARACTERES UTILIZADO NO BRASIL:
) DEFAULT CHARSET = UTF8; 
