/*
* Desafio de Programação ( Academia Técnica ProWay - Capgemini)
* Parte II: Sistema de Cadastro de Anúncios
* @author: Ricardo Barbosa de Oliveira

* Este código consiste no deenvolvimento de um Sistema de Cadastro de Anúncios, 
* como parte de um desafio classificatório para a Academia Técnica ProWay - Capgemini.
*
* Este sistema permite o cadastro de Anúncios contendo os seguintes dados:
* - Nome do Anúncio;
* - Cliente;
* - Data de Início;
* - Data de Término;
* - Investimento por dia.
*
* Fornece o relatório de cada Anúncio contendo:
* - Valor Total Investido;
* - Quantidade Máxima de Visualizações;
* - Quantidade Máxima de Cliques;
* - Quantidade Máxima de Compartilhamentos.
*
* Além disso, permite o filtro por Clientes.
*
 */
package views;

import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Anuncio;
import model.dao.AnuncioDAO;

/**
 *
 * @author Ricardo
 */
public class TelaCadastroAnuncio extends javax.swing.JInternalFrame {

    /**
     * Creates new form _TelaCadastro
     */
    public TelaCadastroAnuncio() {
        initComponents();

        readJTable();
    }

    public void readJTable() {

        // Pega o Modelo da Tabela:
        DefaultTableModel modelo = (DefaultTableModel) jTAnuncios.getModel();

        modelo.setNumRows(0); // Evita a dublicação na exibição dos dados na tabela.

        AnuncioDAO adao = new AnuncioDAO();

        // Laço de repetição para percorrer a Lista:
        for (Anuncio a : adao.read()) {

            // Adiciona os dados do Banco de Dados na Tabela JTAnuncios:
            modelo.addRow(new Object[]{
                a.getID(),
                a.getNOME_ANUNCIO(),
                a.getCLIENTE(),
                a.getDATA_INICIO_BD(),
                a.getDATA_TERMINO_BD(),
                a.getVALOR_INVEST_DIA()

            });
        }

    }

    public void readJTableForClient(String client) {

        // Pega o Modelo da Tabela:
        DefaultTableModel modelo = (DefaultTableModel) jTAnuncios.getModel();

        modelo.setNumRows(0); // Evita a dublicação na exibição dos dados na tabela.

        AnuncioDAO adao = new AnuncioDAO();

        // Laço de repetição para percorrer a Lista:
        for (Anuncio a : adao.readForClient(client)) {

            // Adiciona os dados do Banco de Dados na Tabela JTAnuncios:
            modelo.addRow(new Object[]{
                a.getID(),
                a.getNOME_ANUNCIO(),
                a.getCLIENTE(),
                a.getDATA_INICIO_BD(),
                a.getDATA_TERMINO_BD(),
                a.getVALOR_INVEST_DIA()

            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelNomeAnuncio = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelDataInicio = new javax.swing.JLabel();
        jLabelDataTermino = new javax.swing.JLabel();
        jLabelInvest_Dia = new javax.swing.JLabel();
        txtNomeAnuncio = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtValorDia = new javax.swing.JTextField();
        txtDataInicio = new javax.swing.JFormattedTextField();
        txtDataTermino = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomeAnuncioVazio = new javax.swing.JLabel();
        txtClienteVazio = new javax.swing.JLabel();
        txtValorDiaVazio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAnuncios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotalInvestido = new javax.swing.JTextField();
        txtQtdeMaxVisual = new javax.swing.JTextField();
        txtQtdeMaxCliques = new javax.swing.JTextField();
        txtQtdeMaxCompart = new javax.swing.JTextField();
        txtIdRelatorio = new javax.swing.JTextField();
        txtNomeAnuncioRelatorio = new javax.swing.JTextField();
        txtClienteRelatorio = new javax.swing.JTextField();
        txtDataInicioRelatorio = new javax.swing.JTextField();
        txtDataTerminoRelatorio = new javax.swing.JTextField();
        txtValorDiaRelatorio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnGerarRetorio = new javax.swing.JButton();
        jLabelCampoObrigatorio = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnFiltrarCliente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtClienteFiltro = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setTitle("Cadastrar Anúncio");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Principais"));

        jLabelNomeAnuncio.setText("Nome do Anúncio");

        jLabelCliente.setText("Cliente");

        jLabelDataInicio.setText("Data Início");

        jLabelDataTermino.setText("Data Término");

        jLabelInvest_Dia.setText("Invenstimento por Dia R$");

        txtValorDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorDiaKeyTyped(evt);
            }
        });

        try {
            txtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCadastrar.setBackground(new java.awt.Color(51, 102, 255));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");

        txtNomeAnuncioVazio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNomeAnuncioVazio.setForeground(new java.awt.Color(255, 0, 0));

        txtClienteVazio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtClienteVazio.setForeground(new java.awt.Color(255, 0, 0));

        txtValorDiaVazio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtValorDiaVazio.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNomeAnuncio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNomeAnuncio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtNomeAnuncioVazio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClienteVazio, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDataInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDataTermino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorDia)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelInvest_Dia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addComponent(txtValorDiaVazio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInvest_Dia)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataTermino)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomeAnuncio)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCliente)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataInicio)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorDiaVazio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAnuncioVazio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btnCadastrar))
                    .addComponent(txtClienteVazio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Anúncios Cadastrados"));

        jTAnuncios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome do Anúncio", "Cliente", "Data Início", "Data Término", "Investimento por dia R$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTAnuncios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório do Anúncio"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Valor Total Investido R$");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Qtde. Máx. Visualizações");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Qtde. Máx. Cliques");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Qtde. Máx. Compartilhamentos");

        txtTotalInvestido.setEditable(false);
        txtTotalInvestido.setBackground(new java.awt.Color(102, 102, 102));
        txtTotalInvestido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalInvestido.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalInvestido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtQtdeMaxVisual.setEditable(false);
        txtQtdeMaxVisual.setBackground(new java.awt.Color(102, 102, 102));
        txtQtdeMaxVisual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQtdeMaxVisual.setForeground(new java.awt.Color(255, 255, 255));
        txtQtdeMaxVisual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtQtdeMaxCliques.setEditable(false);
        txtQtdeMaxCliques.setBackground(new java.awt.Color(102, 102, 102));
        txtQtdeMaxCliques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQtdeMaxCliques.setForeground(new java.awt.Color(255, 255, 255));
        txtQtdeMaxCliques.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtQtdeMaxCompart.setEditable(false);
        txtQtdeMaxCompart.setBackground(new java.awt.Color(102, 102, 102));
        txtQtdeMaxCompart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQtdeMaxCompart.setForeground(new java.awt.Color(255, 255, 255));
        txtQtdeMaxCompart.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtIdRelatorio.setEditable(false);
        txtIdRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        txtIdRelatorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNomeAnuncioRelatorio.setEditable(false);
        txtNomeAnuncioRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeAnuncioRelatorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomeAnuncioRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAnuncioRelatorioActionPerformed(evt);
            }
        });

        txtClienteRelatorio.setEditable(false);
        txtClienteRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        txtClienteRelatorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDataInicioRelatorio.setEditable(false);
        txtDataInicioRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        txtDataInicioRelatorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDataTerminoRelatorio.setEditable(false);
        txtDataTerminoRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        txtDataTerminoRelatorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataTerminoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataTerminoRelatorioActionPerformed(evt);
            }
        });

        txtValorDiaRelatorio.setEditable(false);
        txtValorDiaRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        txtValorDiaRelatorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Id");

        jLabel6.setText("Nome do Anúncio");

        jLabel7.setText("Cliente");

        jLabel8.setText("Data Início");

        jLabel14.setText("Data Término");

        jLabel16.setText("Investimento por Dia R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeAnuncioRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtClienteRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataInicioRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataTerminoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtValorDiaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalInvestido)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQtdeMaxVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQtdeMaxCliques, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQtdeMaxCompart, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel14)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienteRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataInicioRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataTerminoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorDiaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAnuncioRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdeMaxVisual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtQtdeMaxCliques)
                                .addComponent(txtTotalInvestido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtQtdeMaxCompart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );

        btnGerarRetorio.setBackground(new java.awt.Color(51, 51, 51));
        btnGerarRetorio.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarRetorio.setText("Gerar Relatório");
        btnGerarRetorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRetorioActionPerformed(evt);
            }
        });

        jLabelCampoObrigatorio.setText("Campo Obrigatório.");

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");

        btnFiltrarCliente.setBackground(new java.awt.Color(0, 153, 0));
        btnFiltrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrarCliente.setText("Filtrar");
        btnFiltrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarClienteActionPerformed(evt);
            }
        });

        jLabel17.setText("Filtrar por Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGerarRetorio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCampoObrigatorio)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCampoObrigatorio)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarRetorio)
                    .addComponent(btnFiltrarCliente)
                    .addComponent(jLabel17)
                    .addComponent(txtClienteFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        // Verfifica se o usuário preencheu todos os campos:
        if (txtNomeAnuncio.getText() == null || txtNomeAnuncio.getText().trim().equals("")) {
            txtNomeAnuncioVazio.setText("Nome do Anúncio vazio.");

        } else {
            txtNomeAnuncioVazio.setVisible(false);
        }

        if (txtCliente.getText() == null || txtCliente.getText().trim().equals("")) {
            txtClienteVazio.setText("Nome do Cliente vazio.");

        } else {
            txtClienteVazio.setVisible(false);
        }

        if (txtValorDia.getText() == null || txtValorDia.getText().trim().equals("")) {
            txtValorDiaVazio.setText("Investimento por Dia vazio.");

        } else {
            txtValorDiaVazio.setVisible(false);

        }

        if ("  /  /    ".equals(txtDataInicio.getText()) || "  /  /    ".equals(txtDataTermino.getText())) {

            JOptionPane.showMessageDialog(null, "Favor preencher ambas as Datas.", "Erro", JOptionPane.ERROR_MESSAGE);

        } else {

            Anuncio a = new Anuncio();
            AnuncioDAO dao = new AnuncioDAO();

            // Formatação dos campos de Data de Início e Término:   
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataInicio = LocalDate.parse(txtDataInicio.getText(), formato);
            LocalDate dataTermino = LocalDate.parse(txtDataTermino.getText(), formato);

            // Compara se a Data Término é menor ou igual a Data Início:
            if (dataTermino.compareTo(dataInicio) <= 0) {

                JOptionPane.showMessageDialog(null, "Data Término tem que ser maior que Data Início.", "Erro", JOptionPane.ERROR_MESSAGE);

            } else {
                // Pegando os valores do Formulário:
                a.setNOME_ANUNCIO(txtNomeAnuncio.getText());
                a.setCLIENTE(txtCliente.getText());
                a.setDATA_INICIO(dataInicio);
                a.setDATA_TERMINO(dataTermino);
                a.setVALOR_INVEST_DIA(Integer.parseInt(txtValorDia.getText()));

                // Envia os dados do Formuário para a Classe AnuncioDAO:
                dao.create(a);

                // Lê o que foi cadastrado no Banco:
                readJTable();

                // Limpa os campos do formulário para um novo cadastro:
                txtNomeAnuncio.setText("");
                txtCliente.setText("");
                txtDataInicio.setText("");
                txtDataTermino.setText("");
                txtValorDia.setText("");

                // Limpa os campos de erro:
                txtNomeAnuncioVazio.setText("");
                txtClienteVazio.setText("");
                txtValorDiaVazio.setText("");
            }

        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnGerarRetorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRetorioActionPerformed

        // Verifica se o usuário selecionou alguma linha na Tabela: 
        if (jTAnuncios.getSelectedRow() == - 1) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um Anúncio Cadastrado para Gerar o Relatório.");

        } else {

            // Pega os dados vindos da Tabela jTAnuncios:
            txtIdRelatorio.setText(jTAnuncios.getValueAt(jTAnuncios.getSelectedRow(), 0).toString());
            txtNomeAnuncioRelatorio.setText(jTAnuncios.getValueAt(jTAnuncios.getSelectedRow(), 1).toString());
            txtClienteRelatorio.setText(jTAnuncios.getValueAt(jTAnuncios.getSelectedRow(), 2).toString());

            // Formatando as Datas vindas da Tabela JTAnuncios:
            DateTimeFormatter formatoDesejado = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataInicioRelatorio = LocalDate.parse(jTAnuncios.getValueAt(jTAnuncios.getSelectedRow(), 3).toString());
            LocalDate dataTerminoRelatorio = LocalDate.parse(jTAnuncios.getValueAt(jTAnuncios.getSelectedRow(), 4).toString());

            txtDataInicioRelatorio.setText(formatoDesejado.format(dataInicioRelatorio));
            txtDataTerminoRelatorio.setText(formatoDesejado.format(dataTerminoRelatorio));

            txtValorDiaRelatorio.setText(jTAnuncios.getValueAt(jTAnuncios.getSelectedRow(), 5).toString());

            // Calcula o período entre as datas:
            Period periodo = Period.between(dataInicioRelatorio, dataTerminoRelatorio);
            int dias = periodo.getDays();
            int meses = periodo.getMonths();

            // Cálculo do período Total de Dias, convencionando cada mês com 30 dias:
            int qtdeTotalDias = dias + (meses * 30);

            int valorDia = Integer.parseInt(txtValorDiaRelatorio.getText());

            // Cálculo do Valor Total Investido, com base no período do Anúncio:
            int valorTotalInvestido = qtdeTotalDias * valorDia;

            /* Com base no cálculo da Calculadora de Anúncio, chegou-se a seguinte conclusão:
           Com R$ 1 investido, tem-se uma quantidade máxima aproximada de 116 visualizações por dia,
           considerando o anúncio original + compartilhamentos.*/
            int qtdeMinVisual = 116;

            int qtdeMaxVisual = (valorTotalInvestido * qtdeMinVisual) * qtdeTotalDias;

            // Com R$ 1 investido, tem-se uma quantidade máxima de 4 cliques por dia:
            int qtdeMinCliques = 4;

            // Cálculo da Quantidade Máxima de Cliques:
            int qtdeMaxCliqes = (valorTotalInvestido * qtdeMinCliques) * qtdeTotalDias;

            // Com R4 1 investido, tem-se a quantidade de 0.54 compartilhamentos:
            float qtdeMinCompart = (float) 0.54;

            // Cálculo da Quantidade Máxima Aproximada de Compartilhamentos:
            int qtdeMaxCompart = Math.round(valorTotalInvestido * qtdeMinCompart) * qtdeTotalDias;

            // Insere os valores caculados nos campos do Relatório:
            txtTotalInvestido.setText(String.valueOf(valorTotalInvestido));
            txtQtdeMaxVisual.setText(String.valueOf(qtdeMaxVisual));
            txtQtdeMaxCliques.setText(String.valueOf(qtdeMaxCliqes));
            txtQtdeMaxCompart.setText(String.valueOf(qtdeMaxCompart));

        }


    }//GEN-LAST:event_btnGerarRetorioActionPerformed

    private void txtDataTerminoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataTerminoRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataTerminoRelatorioActionPerformed

    private void txtNomeAnuncioRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAnuncioRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAnuncioRelatorioActionPerformed

    private void btnFiltrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarClienteActionPerformed

        // Pega o nome do Cliente digitado no campo de filtro:
        readJTableForClient(txtClienteFiltro.getText());


    }//GEN-LAST:event_btnFiltrarClienteActionPerformed

    private void txtValorDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDiaKeyTyped

        // caracteres permitidos dentro do campo:
        String caracteres = "0123456789";

        // Verifica se os caracteres digitados são diferentes dos números permitidos:
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            // não executa o evento.
            evt.consume();
        }
    }//GEN-LAST:event_txtValorDiaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFiltrarCliente;
    private javax.swing.JButton btnGerarRetorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCampoObrigatorio;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelDataInicio;
    private javax.swing.JLabel jLabelDataTermino;
    private javax.swing.JLabel jLabelInvest_Dia;
    private javax.swing.JLabel jLabelNomeAnuncio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTAnuncios;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtClienteFiltro;
    private javax.swing.JTextField txtClienteRelatorio;
    private javax.swing.JLabel txtClienteVazio;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JTextField txtDataInicioRelatorio;
    private javax.swing.JFormattedTextField txtDataTermino;
    private javax.swing.JTextField txtDataTerminoRelatorio;
    private javax.swing.JTextField txtIdRelatorio;
    private javax.swing.JTextField txtNomeAnuncio;
    private javax.swing.JTextField txtNomeAnuncioRelatorio;
    private javax.swing.JLabel txtNomeAnuncioVazio;
    private javax.swing.JTextField txtQtdeMaxCliques;
    private javax.swing.JTextField txtQtdeMaxCompart;
    private javax.swing.JTextField txtQtdeMaxVisual;
    private javax.swing.JTextField txtTotalInvestido;
    private javax.swing.JTextField txtValorDia;
    private javax.swing.JTextField txtValorDiaRelatorio;
    private javax.swing.JLabel txtValorDiaVazio;
    // End of variables declaration//GEN-END:variables

    private void centralizaForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
